In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Pizza Data.csv')
df.head()

          Company          Pizza Name           Type          Size   Price
0  Domino's Pizza         Hand Tossed  Cheeses Pizza   Small (10")  $5.99
1  Domino's Pizza         Hand Tossed  Cheeses Pizza  Medium (12")  $7.99
2  Domino's Pizza         Hand Tossed  Cheeses Pizza   Large (14")  $9.99
3  Domino's Pizza        Handmade Pan  Cheeses Pizza  Medium (12")  $7.99
4  Domino's Pizza  Crunchy Thin Crust  Cheeses Pizza   Small (10")  $5.99

In [3]:
df.shape

(371, 5)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371 entries, 0 to 370
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Company     371 non-null    object
 1   Pizza Name  371 non-null    object
 2   Type        371 non-null    object
 3   Size        371 non-null    object
 4   Price       371 non-null    object
dtypes: object(5)
memory usage: 14.6+ KB

In [5]:
df.isnull().sum()

Company       0
Pizza Name    0
Type          0
Size          0
Price         0
dtype: int64

# Label Encoder

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
label=LabelEncoder()

In [8]:
df.Company =label.fit_transform(df['Company'])

In [9]:
df.Company

0      0
1      0
2      0
3      0
4      0
      ..
366    2
367    2
368    2
369    2
370    2
Name: Company, Length: 371, dtype: int32

In [10]:
df['Pizza Name']=label.fit_transform(df['Pizza Name'])

In [11]:
df['Pizza Name']

0      96
1      96
2      96
3      98
4      75
       ..
366    15
367    82
368    82
369    82
370    82
Name: Pizza Name, Length: 371, dtype: int32

In [12]:
df.Type=label.fit_transform(df['Type'])

In [13]:
df.Type

0      1
1      1
2      1
3      1
4      1
      ..
366    8
367    8
368    8
369    8
370    8
Name: Type, Length: 371, dtype: int32

In [14]:
df.Size=label.fit_transform(df['Size'])

In [15]:
df.Size

0      8
1      4
2      2
3      4
4      8
      ..
366    9
367    8
368    4
369    2
370    9
Name: Size, Length: 371, dtype: int32

In [16]:
df

     Company  Pizza Name  Type  Size    Price
0          0          96     1     8   $5.99
1          0          96     1     4   $7.99
2          0          96     1     2   $9.99
3          0          98     1     4   $7.99
4          0          75     1     8   $5.99
..       ...         ...   ...   ...      ...
366        2          15     8     9  $23.85
367        2          82     8     8  $11.80
368        2          82     8     4  $14.95
369        2          82     8     2  $18.65
370        2          82     8     9  $22.30

[371 rows x 5 columns]

# one Hot Encoding

In [17]:
df=pd.read_csv('Pizza Data.csv')
df

,Company,Pizza Name,Type,Size,Price
0,Domino's Pizza,Hand Tossed,Cheeses Pizza,"Small (10"")",$5.99
1,Domino's Pizza,Hand Tossed,Cheeses Pizza,"Medium (12"")",$7.99
2,Domino's Pizza,Hand Tossed,Cheeses Pizza,"Large (14"")",$9.99
3,Domino's Pizza,Handmade Pan,Cheeses Pizza,"Medium (12"")",$7.99
4,Domino's Pizza,Crunchy Thin Crust,Cheeses Pizza,"Small (10"")",$5.99
...,...,...,...,...,...
366,IMO's Pizza,BBQ Chicken Pizza,Specialty Pizzas,"X Large (16"")",$23.85
367,IMO's Pizza,Egg-Ceptional Pizza,Specialty Pizzas,"Small (10"")",$11.80
368,IMO's Pizza,Egg-Ceptional Pizza,Specialty Pizzas,"Medium (12"")",$14.95
369,IMO's Pizza,Egg-Ceptional Pizza,Specialty Pizzas,"Large (14"")",$18.65
370,IMO's Pizza,Egg-Ceptional Pizza,Specialty Pizzas,"X Large (16"")",$22.30

In [18]:
dummy=pd.get_dummies(df.Company)

In [19]:
dummy.head()

   Domino's Pizza  Godfather's Pizza  IMO's Pizza  Pizza Hut
0               1                  0            0          0
1               1                  0            0          0
2               1                  0            0          0
3               1                  0            0          0
4               1                  0            0          0

In [20]:
dummy=pd.get_dummies(df.Company,drop_first=True)

In [21]:
dummy.head()

   Godfather's Pizza  IMO's Pizza  Pizza Hut
0                  0            0          0
1                  0            0          0
2                  0            0          0
3                  0            0          0
4                  0            0          0

In [22]:
df=df.drop('Company',axis=1)

In [23]:
df.head()

           Pizza Name           Type          Size   Price
0         Hand Tossed  Cheeses Pizza   Small (10")  $5.99
1         Hand Tossed  Cheeses Pizza  Medium (12")  $7.99
2         Hand Tossed  Cheeses Pizza   Large (14")  $9.99
3        Handmade Pan  Cheeses Pizza  Medium (12")  $7.99
4  Crunchy Thin Crust  Cheeses Pizza   Small (10")  $5.99

In [24]:
df=pd.concat([df,dummy],axis=1)
df.head()

,Pizza Name,Type,Size,Price,Godfather's Pizza,IMO's Pizza,Pizza Hut
0,Hand Tossed,Cheeses Pizza,"Small (10"")",$5.99,0,0,0
1,Hand Tossed,Cheeses Pizza,"Medium (12"")",$7.99,0,0,0
2,Hand Tossed,Cheeses Pizza,"Large (14"")",$9.99,0,0,0
3,Handmade Pan,Cheeses Pizza,"Medium (12"")",$7.99,0,0,0
4,Crunchy Thin Crust,Cheeses Pizza,"Small (10"")",$5.99,0,0,0

In [25]:
dummy1=pd.get_dummies(df['Pizza Name'])

In [26]:
dummy1.head()

,7-Alarm Fire™ (Hand-Tossed),All Meat Pizza,All-Meat Combo Pizza (Mozza-Loaded Crust),All-Meat Combo Pizza (Original Crust),All-Meat Combo Pizza (Original or Golden Crust),"All-Meat Combo Pizza (Original, Golden or Thin Crust)",America's Favorite Feast® (Brooklyn Style),America's Favorite Feast® (Gluten Free Crust),America's Favorite Feast® (Hand Tossed or Thin Crust),"America's Favorite Feast® (Hand Tossed, Thin Crust or Brooklyn Style)",...,Veggie Pie Pizza (Original Crust),Veggie Pie Pizza (Original or Golden Crust),Veggie Pie Pizza (Original or Thin Crust),"Veggie Pie Pizza (Original, Golden or Thin Crust)",Veggie Pizza,Wisconsin 6 Cheese (Brooklyn Style),Wisconsin 6 Cheese (Gluten Free Crust),Wisconsin 6 Cheese (Hand Tossed or Thin Crust),"Wisconsin 6 Cheese (Hand Tossed, Handmade Pan or Thin Crust)","Wisconsin 6 Cheese (Hand Tossed, Thin Crust or Brooklyn Style)"
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
dummy1=pd.get_dummies(df['Pizza Name'],drop_first=True)

In [28]:
dummy1.head()

,All Meat Pizza,All-Meat Combo Pizza (Mozza-Loaded Crust),All-Meat Combo Pizza (Original Crust),All-Meat Combo Pizza (Original or Golden Crust),"All-Meat Combo Pizza (Original, Golden or Thin Crust)",America's Favorite Feast® (Brooklyn Style),America's Favorite Feast® (Gluten Free Crust),America's Favorite Feast® (Hand Tossed or Thin Crust),"America's Favorite Feast® (Hand Tossed, Thin Crust or Brooklyn Style)",America's Favorite Feast® (Handmade Pan),...,Veggie Pie Pizza (Original Crust),Veggie Pie Pizza (Original or Golden Crust),Veggie Pie Pizza (Original or Thin Crust),"Veggie Pie Pizza (Original, Golden or Thin Crust)",Veggie Pizza,Wisconsin 6 Cheese (Brooklyn Style),Wisconsin 6 Cheese (Gluten Free Crust),Wisconsin 6 Cheese (Hand Tossed or Thin Crust),"Wisconsin 6 Cheese (Hand Tossed, Handmade Pan or Thin Crust)","Wisconsin 6 Cheese (Hand Tossed, Thin Crust or Brooklyn Style)"
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
df=df.drop(['Pizza Name'],axis=1)

In [30]:
df.head()

,Type,Size,Price,Godfather's Pizza,IMO's Pizza,Pizza Hut
0,Cheeses Pizza,"Small (10"")",$5.99,0,0,0
1,Cheeses Pizza,"Medium (12"")",$7.99,0,0,0
2,Cheeses Pizza,"Large (14"")",$9.99,0,0,0
3,Cheeses Pizza,"Medium (12"")",$7.99,0,0,0
4,Cheeses Pizza,"Small (10"")",$5.99,0,0,0

In [31]:
df=pd.concat([df,dummy1],axis=1)
df.head()

,Type,Size,Price,Godfather's Pizza,IMO's Pizza,Pizza Hut,All Meat Pizza,All-Meat Combo Pizza (Mozza-Loaded Crust),All-Meat Combo Pizza (Original Crust),All-Meat Combo Pizza (Original or Golden Crust),...,Veggie Pie Pizza (Original Crust),Veggie Pie Pizza (Original or Golden Crust),Veggie Pie Pizza (Original or Thin Crust),"Veggie Pie Pizza (Original, Golden or Thin Crust)",Veggie Pizza,Wisconsin 6 Cheese (Brooklyn Style),Wisconsin 6 Cheese (Gluten Free Crust),Wisconsin 6 Cheese (Hand Tossed or Thin Crust),"Wisconsin 6 Cheese (Hand Tossed, Handmade Pan or Thin Crust)","Wisconsin 6 Cheese (Hand Tossed, Thin Crust or Brooklyn Style)"
0,Cheeses Pizza,"Small (10"")",$5.99,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Cheeses Pizza,"Medium (12"")",$7.99,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Cheeses Pizza,"Large (14"")",$9.99,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Cheeses Pizza,"Medium (12"")",$7.99,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Cheeses Pizza,"Small (10"")",$5.99,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
dummy2=pd.get_dummies(df.Type)

In [33]:
dummy2.head()

,Cheese Pizza,Cheeses Pizza,Classic Recipe Pizzas,Express Favorites,Feast Pizzas,Gluten-Free Pizzas,New Recipe Pizzas,Skinny Pizzas,Specialty Pizzas
0,0,1,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0

In [34]:
dummy2=pd.get_dummies(df.Type,drop_first=True)

In [35]:
dummy2.head()

,Cheeses Pizza,Classic Recipe Pizzas,Express Favorites,Feast Pizzas,Gluten-Free Pizzas,New Recipe Pizzas,Skinny Pizzas,Specialty Pizzas
0,1,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0

In [36]:
df=df.drop('Type',axis=1)

In [37]:
df.head()

,Size,Price,Godfather's Pizza,IMO's Pizza,Pizza Hut,All Meat Pizza,All-Meat Combo Pizza (Mozza-Loaded Crust),All-Meat Combo Pizza (Original Crust),All-Meat Combo Pizza (Original or Golden Crust),"All-Meat Combo Pizza (Original, Golden or Thin Crust)",...,Veggie Pie Pizza (Original Crust),Veggie Pie Pizza (Original or Golden Crust),Veggie Pie Pizza (Original or Thin Crust),"Veggie Pie Pizza (Original, Golden or Thin Crust)",Veggie Pizza,Wisconsin 6 Cheese (Brooklyn Style),Wisconsin 6 Cheese (Gluten Free Crust),Wisconsin 6 Cheese (Hand Tossed or Thin Crust),"Wisconsin 6 Cheese (Hand Tossed, Handmade Pan or Thin Crust)","Wisconsin 6 Cheese (Hand Tossed, Thin Crust or Brooklyn Style)"
0,"Small (10"")",$5.99,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,"Medium (12"")",$7.99,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,"Large (14"")",$9.99,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,"Medium (12"")",$7.99,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,"Small (10"")",$5.99,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [38]:
df=pd.concat([df,dummy2],axis=1)
df.head()

,Size,Price,Godfather's Pizza,IMO's Pizza,Pizza Hut,All Meat Pizza,All-Meat Combo Pizza (Mozza-Loaded Crust),All-Meat Combo Pizza (Original Crust),All-Meat Combo Pizza (Original or Golden Crust),"All-Meat Combo Pizza (Original, Golden or Thin Crust)",...,"Wisconsin 6 Cheese (Hand Tossed, Handmade Pan or Thin Crust)","Wisconsin 6 Cheese (Hand Tossed, Thin Crust or Brooklyn Style)",Cheeses Pizza,Classic Recipe Pizzas,Express Favorites,Feast Pizzas,Gluten-Free Pizzas,New Recipe Pizzas,Skinny Pizzas,Specialty Pizzas
0,"Small (10"")",$5.99,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,"Medium (12"")",$7.99,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,"Large (14"")",$9.99,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,"Medium (12"")",$7.99,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,"Small (10"")",$5.99,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [39]:
dummy3=pd.get_dummies(df.Size)

In [40]:
dummy3.head()

,Jumbo,Large,"Large (14"")",Medium,"Medium (12"")",Mini,Personal,Small,"Small (10"")","X Large (16"")","X-Large (16"")"
0,0,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,1,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,1,0,0

In [41]:
dummy3=pd.get_dummies(df.Size,drop_first=True)

In [42]:
dummy3.head()

,Large,"Large (14"")",Medium,"Medium (12"")",Mini,Personal,Small,"Small (10"")","X Large (16"")","X-Large (16"")"
0,0,0,0,0,0,0,0,1,0,0
1,0,0,0,1,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0

In [43]:
df=df.drop('Size',axis=1)

In [44]:
df.head()

,Price,Godfather's Pizza,IMO's Pizza,Pizza Hut,All Meat Pizza,All-Meat Combo Pizza (Mozza-Loaded Crust),All-Meat Combo Pizza (Original Crust),All-Meat Combo Pizza (Original or Golden Crust),"All-Meat Combo Pizza (Original, Golden or Thin Crust)",America's Favorite Feast® (Brooklyn Style),...,"Wisconsin 6 Cheese (Hand Tossed, Handmade Pan or Thin Crust)","Wisconsin 6 Cheese (Hand Tossed, Thin Crust or Brooklyn Style)",Cheeses Pizza,Classic Recipe Pizzas,Express Favorites,Feast Pizzas,Gluten-Free Pizzas,New Recipe Pizzas,Skinny Pizzas,Specialty Pizzas
0,$5.99,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,$7.99,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,$9.99,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,$7.99,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,$5.99,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [45]:
df=pd.concat([df,dummy3],axis=1)
df.head()

,Price,Godfather's Pizza,IMO's Pizza,Pizza Hut,All Meat Pizza,All-Meat Combo Pizza (Mozza-Loaded Crust),All-Meat Combo Pizza (Original Crust),All-Meat Combo Pizza (Original or Golden Crust),"All-Meat Combo Pizza (Original, Golden or Thin Crust)",America's Favorite Feast® (Brooklyn Style),...,Large,"Large (14"")",Medium,"Medium (12"")",Mini,Personal,Small,"Small (10"")","X Large (16"")","X-Large (16"")"
0,$5.99,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,$7.99,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,$9.99,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,$7.99,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,$5.99,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

# ordinal Encoding

In [46]:
df=pd.read_csv('Pizza Data.csv')
df.head()

          Company          Pizza Name           Type          Size   Price
0  Domino's Pizza         Hand Tossed  Cheeses Pizza   Small (10")  $5.99
1  Domino's Pizza         Hand Tossed  Cheeses Pizza  Medium (12")  $7.99
2  Domino's Pizza         Hand Tossed  Cheeses Pizza   Large (14")  $9.99
3  Domino's Pizza        Handmade Pan  Cheeses Pizza  Medium (12")  $7.99
4  Domino's Pizza  Crunchy Thin Crust  Cheeses Pizza   Small (10")  $5.99

In [47]:
df.Company.unique()

array(["Domino's Pizza", 'Pizza Hut', "Godfather's Pizza", "IMO's Pizza"],
      dtype=object)

In [48]:
df['Pizza Name'].unique()

array(['Hand Tossed', 'Handmade Pan', 'Crunchy Thin Crust',
       'Brooklyn Style', 'Gluten Free Crust',
       'Spinach & Feta (Hand Tossed or Thin Crust)',
       'Spinach & Feta (Hand Tossed, Handmade Pan or Thin Crust)',
       'Spinach & Feta (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Spinach & Feta (Brooklyn Style)',
       'Spinach & Feta (Gluten Free Crust)',
       'Wisconsin 6 Cheese (Hand Tossed or Thin Crust)',
       'Wisconsin 6 Cheese (Hand Tossed, Handmade Pan or Thin Crust)',
       'Wisconsin 6 Cheese (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Wisconsin 6 Cheese (Brooklyn Style)',
       'Wisconsin 6 Cheese (Gluten Free Crust)',
       'Honolulu Hawaiian (Hand Tossed or Thin Crust)',
       'Honolulu Hawaiian (Hand Tossed, Handmade Pan or Thin Crust)',
       'Honolulu Hawaiian (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Honolulu Hawaiian (Brooklyn Style)',
       'Honolulu Hawaiian (Gluten Free Crust)',
       'Philly Cheese Steak (Hand Tossed or Thin Crust)',
       'Philly Cheese Steak (Hand Tossed, Handmade Pan or Thin Crust)',
       'Philly Cheese Steak (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Philly Cheese Steak (Brooklyn Style)',
       'Philly Cheese Steak (Gluten Free Crust)',
       'Pacific Veggie (Hand Tossed or Thin Crust)',
       'Pacific Veggie (Hand Tossed, Handmade Pan or Thin Crust)',
       'Pacific Veggie (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Pacific Veggie (Brooklyn Style)',
       'Pacific Veggie (Gluten Free Crust)',
       'Cali Chicken Bacon Ranch™ (Hand Tossed or Thin Crust)',
       'Cali Chicken Bacon Ranch™ (Hand Tossed, Handmade Pan or Thin Crust)',
       'Cali Chicken Bacon Ranch™ (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Cali Chicken Bacon Ranch™ (Brooklyn Style)',
       'Cali Chicken Bacon Ranch™ (Gluten Free Crust)',
       'Fiery Hawaiian™ (Hand Tossed or Thin Crust)',
       'Fiery Hawaiian™ (Hand Tossed, Handmade Pan or Thin Crust)',
       'Fiery Hawaiian™ (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Fiery Hawaiian™ (Brooklyn Style)',
       'Fiery Hawaiian™ (Gluten Free Crust)',
       'Buffalo Chicken (Hand Tossed or Thin Crust)',
       'Buffalo Chicken (Hand Tossed, Handmade Pan or Thin Crust)',
       'Buffalo Chicken (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Buffalo Chicken (Brooklyn Style)',
       'Buffalo Chicken (Gluten Free Crust)',
       'Memphis BBQ Chicken (Hand Tossed or Thin Crust)',
       'Memphis BBQ Chicken (Hand Tossed, Hnadmade Pan or Thin Crust)',
       'Memphis BBQ Chicken (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Memphis BBQ Chicken (Brooklyn Style)',
       'Memphis BBQ Chicken (Gluten Free Crust)',
       "America's Favorite Feast® (Hand Tossed or Thin Crust)",
       "America's Favorite Feast® (Handmade Pan)",
       "America's Favorite Feast® (Hand Tossed, Thin Crust or Brooklyn Style)",
       "America's Favorite Feast® (Brooklyn Style)",
       "America's Favorite Feast® (Gluten Free Crust)",
       'Bacon Cheeseburger Feast® (Hand Tossed or Thin Crust)',
       'Bacon Cheeseburger Feast® (Handmade Pan)',
       'Bacon Cheeseburger Feast® (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Bacon Cheeseburger Feast® (Brooklyn Style)',
       'Bacon Cheeseburger Feast® (Gluten Free Crust)',
       'Deluxe Feast® (Hand Tossed or Thin Crust)',
       'Deluxe Feast® (Handmade Pan)',
       'Deluxe Feast® (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Deluxe Feast® (Brooklyn Style)',
       'Deluxe Feast® (Gluten Free Crust)',
       'ExtravaganZZa Feast® (Hand Tossed or Thin Crust)',
       'ExtravaganZZa Feast® (Hand Tossed, Handmade Pan or Thin Crust)',
       'ExtravaganZZa Feast® (Hand Tossed, Thin Crust or Brooklyn Style)',
       'ExtravaganZZa Feast® (Brooklyn Style)',
       'ExtravaganZZa Feast® (Gluten Free Crust)',
       'MeatZZa Feast® (Hand Tossed or Thin Crust)',
       'MeatZZa Feast® (Hand Tossed, Handmade Pan or Thin Crust)',
       'MeatZZa Feast® (Hand Tossed, Thin Crust or Brooklyn Style)',
       'MeatZZa Feast® (Brooklyn Style)',
       'MeatZZa Feast® (Gluten Free Crust)',
       'Ultimate Pepperoni Feast™ (Hand Tossed or Thin Crust)',
       'Ultimate Pepperoni Feast™ (Hand Tossed, Handmade Pan or Thin Crust)',
       'Ultimate Pepperoni Feast™ (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Ultimate Pepperoni Feast™ (Brooklyn Style)',
       'Ultimate Pepperoni Feast™ (Gluten Free Crust)', 'Hand-Tossed',
       'Pan Pizza', 'Thin N Crispy', 'Stuffed Crust', 'Skinny Slice',
       "Pepperoni Lover's® Pizza (Hand-Tossed)",
       "Pepperoni Lover's® Pizza (Pan Pizza)",
       "Pepperoni Lover's® Pizza (Thin N Crispy)",
       "Pepperoni Lover's® Pizza (Stuffed Crust)",
       "Pepperoni Lover's® Pizza (Skinny Slice)",
       "Meat Lover's® Pizza (Hand-Tossed)",
       "Meat Lover's® Pizza (Pan Pizza)",
       "Meat Lover's® Pizza (Thin N Crispy)",
       "Meat Lover's® Pizza (Stuffed Crust)",
       "Meat Lover's® Pizza (Skinny Slice)",
       "Ultimate Cheese Lover's Pizza (Hand-Tossed)",
       "Ultimate Cheese Lover's Pizza (Pan Pizza)",
       "Ultimate Cheese Lover's Pizza (Thin N Crispy)",
       "Ultimate Cheese Lover's Pizza (Stuffed Crust)",
       "Ultimate Cheese Lover's Pizza (Skinny Slice)",
       "Veggie Lover's® Pizza (Hand-Tossed)",
       "Veggie Lover's® Pizza (Pan Pizza)",
       "Veggie Lover's® Pizza (Thin N Crispy)",
       "Veggie Lover's® Pizza (Stuffed Crust)",
       "Veggie Lover's® Pizza (Skinny Slice)",
       'Supreme Pizza (Hand-Tossed)', 'Supreme Pizza (Pan Pizza)',
       'Supreme Pizza (Thin N Crispy)', 'Supreme Pizza (Stuffed Crust)',
       'Supreme Pizza (Skinny Slice)', "BBQ Lover's™ (Hand-Tossed)",
       "BBQ Lover's™ (Pan Pizza)", "BBQ Lover's™ (Thin N Crispy)",
       "BBQ Lover's™ (Stuffed Crust)", "BBQ Lover's™ (Skinny Slice)",
       'Chicken Supreme Pizza (Hand-Tossed)',
       'Chicken Supreme Pizza (Pan Pizza)',
       'Chicken Supreme Pizza (Thin N Crispy)',
       'Chicken Supreme Pizza (Stuffed Crust)',
       'Chicken Supreme Pizza (Skinny Slice)',
       'New Primo Meat Pizza (Hand-Tossed)',
       'New Primo Meat Pizza (Pan Pizza)',
       'New Primo Meat Pizza (Thin N Crispy)',
       'New Primo Meat Pizza (Stuffed Crust)',
       'New Primo Meat Pizza (Skinny Slice)',
       'Hawaiian Luau (Hand-Tossed)', 'Hawaiian Luau (Pan Pizza)',
       'Hawaiian Luau (Thin N Crispy)', 'Hawaiian Luau (Stuffed Crust)',
       'Hawaiian Luau (Skinny Slice)',
       'Super Supreme Pizza (Hand-Tossed)',
       'Super Supreme Pizza (Pan Pizza)',
       'Super Supreme Pizza (Thin N Crispy)',
       'Super Supreme Pizza (Stuffed Crust)',
       'Super Supreme Pizza (Skinny Slice)',
       'Garden Party™ (Thin N Crispy)',
       'Old Fashioned Meatbrawl™ (Pan Pizza)',
       'Cock-a-doodle Bacon™ (Hand-Tossed)',
       'Hot and Twisted™ (Hand-Tossed)', 'Pretzel Piggy™ (Hand-Tossed)',
       'BBQ Bacon Cheeseburger (Hand-Tossed)',
       'Giddy-Up BBQ Chicken™ (Hand-Tossed)',
       'Buffalo State of Mind™ (Hand-Tossed)',
       'Cherry Pepper Bombshell™ (Thin N Crispy)',
       '7-Alarm Fire™ (Hand-Tossed)', 'Skinny Beach™ (Skinny Slice)',
       'Skinny With A Kick™ (Skinny Slice)',
       'Skinny Italy (Skinny Slice)', 'Skinny Luau™ (Skinny Slice)',
       'Skinny Club™ (Skinny Slice)',
       'Create Your Own (Gluten-Free Crust)', 'Cheese (Original Crust)',
       'Cheese (Original or Golden Crust)',
       'Cheese (Original, Golden or Thin Crust)',
       'Cheese (Mozza-Loaded Crust)', 'Cheese (Original or Thin Crust)',
       'All-Meat Combo Pizza (Original Crust)',
       'All-Meat Combo Pizza (Original or Golden Crust)',
       'All-Meat Combo Pizza (Original, Golden or Thin Crust)',
       'All-Meat Combo Pizza (Mozza-Loaded Crust)',
       'Bacon Cheeseburger Pizza (Original Crust)',
       'Bacon Cheeseburger Pizza (Original or Golden Crust)',
       'Bacon Cheeseburger Pizza (Original, Golden or Thin Crust)',
       'Bacon Cheeseburger Pizza (Mozza-Loaded Crust)',
       'Bacon Cheeseburger Pizza (Original or Thin Crust)',
       'Taco Pie Pizza (Original Crust)',
       'Taco Pie Pizza (Original or Golden Crust)',
       'Taco Pie Pizza (Original, Golden or Thin Crust)',
       'Taco Pie Pizza (Mozza-Loaded Crust)',
       'Taco Pie Pizza (Original or Thin Crust)',
       'Classic Combo Pizza (Original Crust)',
       'Classic Combo Pizza (Original or Golden Crust)',
       'Classic Combo Pizza (Original, Golden or Thin Crust)',
       'Classic Combo Pizza (Mozza-Loaded Crust)',
       'Classic Combo Pizza (Original or Thin Crust)',
       'Humble Pie Pizza (Original Crust)',
       'Humble Pie Pizza (Original or Golden Crust)',
       'Humble Pie Pizza (Original, Golden or Thin Crust)',
       'Humble Pie Pizza (Mozza-Loaded Crust)',
       'Humble Pie Pizza (Original or Thin Crust)',
       'Veggie Pie Pizza (Original Crust)',
       'Veggie Pie Pizza (Original or Golden Crust)',
       'Veggie Pie Pizza (Original, Golden or Thin Crust)',
       'Veggie Pie Pizza (Mozza-Loaded Crust)',
       'Veggie Pie Pizza (Original or Thin Crust)',
       'Hot Stuff Pizza (Original Crust)',
       'Hot Stuff Pizza (Original or Golden Crust)',
       'Hot Stuff Pizza (Original, Golden or Thin Crust)',
       'Hot Stuff Pizza (Mozza-Loaded Crust)',
       'Hot Stuff Pizza (Original or Thin Crust)',
       'Hawaiian Pizza (Original Crust)',
       'Hawaiian Pizza (Original or Golden Crust)',
       'Hawaiian Pizza (Original, Golden or Thin Crust)',
       'Hawaiian Pizza (Mozza-Loaded Crust)',
       'Hawaiian Pizza (Original or Thin Crust)',
       'BLT Pizza (Original Crust)',
       'BLT Pizza (Original or Golden Crust)',
       'BLT Pizza (Original, Golden or Thin Crust)',
       'BLT Pizza (Mozza-Loaded Crust)',
       'BLT Pizza (Original or Thin Crust)',
       'Buffalo Chicken Pizza (Original Crust)',
       'Buffalo Chicken Pizza (Original or Golden Crust)',
       'Buffalo Chicken Pizza (Original, Golden or Thin Crust)',
       'Buffalo Chicken Pizza (Mozza-Loaded Crust)',
       'Buffalo Chicken Pizza (Original or Thin Crust)',
       'Super Combo Pizza (Original or Golden Crust)',
       'Super Combo Pizza (Original, Golden or Thin Crust)',
       'Super Combo Pizza (Mozza-Loaded Crust)',
       'Super Combo Pizza (Original or Thin Crust)',
       'Super Hawaiian Pizza (Original or Golden Crust)',
       'Super Hawaiian Pizza (Original, Golden or Thin Crust)',
       'Super Hawaiian Pizza (Mozza-Loaded Crust)',
       'Super Hawaiian Pizza (Original or Thin Crust)',
       'Super Taco Pizza (Original or Golden Crust)',
       'Super Taco Pizza (Original, Golden or Thin Crust)',
       'Super Taco Pizza (Mozza-Loaded Crust)',
       'Super Taco Pizza (Original or Thin Crust)',
       'The Don (Original or Golden Crust)',
       'The Don (Original, Golden or Thin Crust)',
       'The Don (Mozza-Loaded Crust)', 'The Don (Original or Thin Crust)',
       'Super Veggie Pizza (Original or Golden Crust)',
       'Super Veggie Pizza (Original, Golden or Thin Crust)',
       'Super Veggie Pizza (Mozza-Loaded Crust)',
       'Super Veggie Pizza (Original or Thin Crust)',
       'BBQ Bacon Cheeseburger Pizza (Original Crust)',
       'BBQ Bacon Cheeseburger Pizza (Original, Golden or Thin Crust)',
       'BBQ Bacon Cheeseburger Pizza (Mozza-Loaded Crust)',
       'Chipotle Chicken and Bacon Pizza (Original Crust)',
       'Chipotle Chicken and Bacon Pizza (Original, Golden or Thin Crust)',
       'Chipotle Chicken and Bacon Pizza (Mozza-Loaded Crust)',
       'Margherita Pizza (Original, Golden or Thin Crust)',
       'Margherita Pizza (Thin Crust)',
       'Margherita Chicken Pizza (Original, Golden or Thin Crust)',
       'Margherita Chicken Pizza (Thin Crust)', 'Thin Crust',
       'Original Crust', 'Original or Golden Crust',
       'Original, Golden or Thin Crust', 'Mozza-Loaded Crust',
       'Original or Thin Crust', 'Deluxe Pizza', 'Veggie Pizza',
       'Cheese Pizza', 'All Meat Pizza', 'BBQ Chicken Pizza',
       'Egg-Ceptional Pizza'], dtype=object)

In [49]:
df.Type.unique()

array(['Cheeses Pizza', 'Specialty Pizzas', 'Feast Pizzas',
       'Cheese Pizza', 'Classic Recipe Pizzas', 'New Recipe Pizzas',
       'Skinny Pizzas', 'Gluten-Free Pizzas', 'Express Favorites'],
      dtype=object)

In [50]:
df.Size.unique()

array(['Small (10")', 'Medium (12")', 'Large (14")', 'X-Large (16")',
       'Medium', 'Large', 'Personal', 'Small', 'Mini', 'Jumbo',
       'X Large (16")'], dtype=object)

In [51]:
from sklearn.preprocessing import OrdinalEncoder

In [52]:
com=["Domino's Pizza", 'Pizza Hut', "Godfather's Pizza", "IMO's Pizza"]
ordinal=OrdinalEncoder(categories=[com])
encoded=ordinal.fit_transform(df[['Company']])

In [53]:
encoded

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.]])

In [54]:
encoded_company = pd.DataFrame(encoded,columns=['Encoded'])

In [55]:
df.Company=encoded_company

In [56]:
df.Company

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
366    3.0
367    3.0
368    3.0
369    3.0
370    3.0
Name: Company, Length: 371, dtype: float64

In [57]:
df.head()

   Company          Pizza Name           Type          Size   Price
0      0.0         Hand Tossed  Cheeses Pizza   Small (10")  $5.99
1      0.0         Hand Tossed  Cheeses Pizza  Medium (12")  $7.99
2      0.0         Hand Tossed  Cheeses Pizza   Large (14")  $9.99
3      0.0        Handmade Pan  Cheeses Pizza  Medium (12")  $7.99
4      0.0  Crunchy Thin Crust  Cheeses Pizza   Small (10")  $5.99

In [58]:
pizza=['Hand Tossed', 'Handmade Pan', 'Crunchy Thin Crust',
       'Brooklyn Style', 'Gluten Free Crust',
       'Spinach & Feta (Hand Tossed or Thin Crust)',
       'Spinach & Feta (Hand Tossed, Handmade Pan or Thin Crust)',
       'Spinach & Feta (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Spinach & Feta (Brooklyn Style)',
       'Spinach & Feta (Gluten Free Crust)',
       'Wisconsin 6 Cheese (Hand Tossed or Thin Crust)',
       'Wisconsin 6 Cheese (Hand Tossed, Handmade Pan or Thin Crust)',
       'Wisconsin 6 Cheese (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Wisconsin 6 Cheese (Brooklyn Style)',
       'Wisconsin 6 Cheese (Gluten Free Crust)',
       'Honolulu Hawaiian (Hand Tossed or Thin Crust)',
       'Honolulu Hawaiian (Hand Tossed, Handmade Pan or Thin Crust)',
       'Honolulu Hawaiian (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Honolulu Hawaiian (Brooklyn Style)',
       'Honolulu Hawaiian (Gluten Free Crust)',
       'Philly Cheese Steak (Hand Tossed or Thin Crust)',
       'Philly Cheese Steak (Hand Tossed, Handmade Pan or Thin Crust)',
       'Philly Cheese Steak (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Philly Cheese Steak (Brooklyn Style)',
       'Philly Cheese Steak (Gluten Free Crust)',
       'Pacific Veggie (Hand Tossed or Thin Crust)',
       'Pacific Veggie (Hand Tossed, Handmade Pan or Thin Crust)',
       'Pacific Veggie (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Pacific Veggie (Brooklyn Style)',
       'Pacific Veggie (Gluten Free Crust)',
       'Cali Chicken Bacon Ranch™ (Hand Tossed or Thin Crust)',
       'Cali Chicken Bacon Ranch™ (Hand Tossed, Handmade Pan or Thin Crust)',
       'Cali Chicken Bacon Ranch™ (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Cali Chicken Bacon Ranch™ (Brooklyn Style)',
       'Cali Chicken Bacon Ranch™ (Gluten Free Crust)',
       'Fiery Hawaiian™ (Hand Tossed or Thin Crust)',
       'Fiery Hawaiian™ (Hand Tossed, Handmade Pan or Thin Crust)',
       'Fiery Hawaiian™ (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Fiery Hawaiian™ (Brooklyn Style)',
       'Fiery Hawaiian™ (Gluten Free Crust)',
       'Buffalo Chicken (Hand Tossed or Thin Crust)',
       'Buffalo Chicken (Hand Tossed, Handmade Pan or Thin Crust)',
       'Buffalo Chicken (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Buffalo Chicken (Brooklyn Style)',
       'Buffalo Chicken (Gluten Free Crust)',
       'Memphis BBQ Chicken (Hand Tossed or Thin Crust)',
       'Memphis BBQ Chicken (Hand Tossed, Hnadmade Pan or Thin Crust)',
       'Memphis BBQ Chicken (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Memphis BBQ Chicken (Brooklyn Style)',
       'Memphis BBQ Chicken (Gluten Free Crust)',
       "America's Favorite Feast® (Hand Tossed or Thin Crust)",
       "America's Favorite Feast® (Handmade Pan)",
       "America's Favorite Feast® (Hand Tossed, Thin Crust or Brooklyn Style)",
       "America's Favorite Feast® (Brooklyn Style)",
       "America's Favorite Feast® (Gluten Free Crust)",
       'Bacon Cheeseburger Feast® (Hand Tossed or Thin Crust)',
       'Bacon Cheeseburger Feast® (Handmade Pan)',
       'Bacon Cheeseburger Feast® (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Bacon Cheeseburger Feast® (Brooklyn Style)',
       'Bacon Cheeseburger Feast® (Gluten Free Crust)',
       'Deluxe Feast® (Hand Tossed or Thin Crust)',
       'Deluxe Feast® (Handmade Pan)',
       'Deluxe Feast® (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Deluxe Feast® (Brooklyn Style)',
       'Deluxe Feast® (Gluten Free Crust)',
       'ExtravaganZZa Feast® (Hand Tossed or Thin Crust)',
       'ExtravaganZZa Feast® (Hand Tossed, Handmade Pan or Thin Crust)',
       'ExtravaganZZa Feast® (Hand Tossed, Thin Crust or Brooklyn Style)',
       'ExtravaganZZa Feast® (Brooklyn Style)',
       'ExtravaganZZa Feast® (Gluten Free Crust)',
       'MeatZZa Feast® (Hand Tossed or Thin Crust)',
       'MeatZZa Feast® (Hand Tossed, Handmade Pan or Thin Crust)',
       'MeatZZa Feast® (Hand Tossed, Thin Crust or Brooklyn Style)',
       'MeatZZa Feast® (Brooklyn Style)',
       'MeatZZa Feast® (Gluten Free Crust)',
       'Ultimate Pepperoni Feast™ (Hand Tossed or Thin Crust)',
       'Ultimate Pepperoni Feast™ (Hand Tossed, Handmade Pan or Thin Crust)',
       'Ultimate Pepperoni Feast™ (Hand Tossed, Thin Crust or Brooklyn Style)',
       'Ultimate Pepperoni Feast™ (Brooklyn Style)',
       'Ultimate Pepperoni Feast™ (Gluten Free Crust)', 'Hand-Tossed',
       'Pan Pizza', 'Thin N Crispy', 'Stuffed Crust', 'Skinny Slice',
       "Pepperoni Lover's® Pizza (Hand-Tossed)",
       "Pepperoni Lover's® Pizza (Pan Pizza)",
       "Pepperoni Lover's® Pizza (Thin N Crispy)",
       "Pepperoni Lover's® Pizza (Stuffed Crust)",
       "Pepperoni Lover's® Pizza (Skinny Slice)",
       "Meat Lover's® Pizza (Hand-Tossed)",
       "Meat Lover's® Pizza (Pan Pizza)",
       "Meat Lover's® Pizza (Thin N Crispy)",
       "Meat Lover's® Pizza (Stuffed Crust)",
       "Meat Lover's® Pizza (Skinny Slice)",
       "Ultimate Cheese Lover's Pizza (Hand-Tossed)",
       "Ultimate Cheese Lover's Pizza (Pan Pizza)",
       "Ultimate Cheese Lover's Pizza (Thin N Crispy)",
       "Ultimate Cheese Lover's Pizza (Stuffed Crust)",
       "Ultimate Cheese Lover's Pizza (Skinny Slice)",
       "Veggie Lover's® Pizza (Hand-Tossed)",
       "Veggie Lover's® Pizza (Pan Pizza)",
       "Veggie Lover's® Pizza (Thin N Crispy)",
       "Veggie Lover's® Pizza (Stuffed Crust)",
       "Veggie Lover's® Pizza (Skinny Slice)",
       'Supreme Pizza (Hand-Tossed)', 'Supreme Pizza (Pan Pizza)',
       'Supreme Pizza (Thin N Crispy)', 'Supreme Pizza (Stuffed Crust)',
       'Supreme Pizza (Skinny Slice)', "BBQ Lover's™ (Hand-Tossed)",
       "BBQ Lover's™ (Pan Pizza)", "BBQ Lover's™ (Thin N Crispy)",
       "BBQ Lover's™ (Stuffed Crust)", "BBQ Lover's™ (Skinny Slice)",
       'Chicken Supreme Pizza (Hand-Tossed)',
       'Chicken Supreme Pizza (Pan Pizza)',
       'Chicken Supreme Pizza (Thin N Crispy)',
       'Chicken Supreme Pizza (Stuffed Crust)',
       'Chicken Supreme Pizza (Skinny Slice)',
       'New Primo Meat Pizza (Hand-Tossed)',
       'New Primo Meat Pizza (Pan Pizza)',
       'New Primo Meat Pizza (Thin N Crispy)',
       'New Primo Meat Pizza (Stuffed Crust)',
       'New Primo Meat Pizza (Skinny Slice)',
       'Hawaiian Luau (Hand-Tossed)', 'Hawaiian Luau (Pan Pizza)',
       'Hawaiian Luau (Thin N Crispy)', 'Hawaiian Luau (Stuffed Crust)',
       'Hawaiian Luau (Skinny Slice)',
       'Super Supreme Pizza (Hand-Tossed)',
       'Super Supreme Pizza (Pan Pizza)',
       'Super Supreme Pizza (Thin N Crispy)',
       'Super Supreme Pizza (Stuffed Crust)',
       'Super Supreme Pizza (Skinny Slice)',
       'Garden Party™ (Thin N Crispy)',
       'Old Fashioned Meatbrawl™ (Pan Pizza)',
       'Cock-a-doodle Bacon™ (Hand-Tossed)',
       'Hot and Twisted™ (Hand-Tossed)', 'Pretzel Piggy™ (Hand-Tossed)',
       'BBQ Bacon Cheeseburger (Hand-Tossed)',
       'Giddy-Up BBQ Chicken™ (Hand-Tossed)',
       'Buffalo State of Mind™ (Hand-Tossed)',
       'Cherry Pepper Bombshell™ (Thin N Crispy)',
       '7-Alarm Fire™ (Hand-Tossed)', 'Skinny Beach™ (Skinny Slice)',
       'Skinny With A Kick™ (Skinny Slice)',
       'Skinny Italy (Skinny Slice)', 'Skinny Luau™ (Skinny Slice)',
       'Skinny Club™ (Skinny Slice)',
       'Create Your Own (Gluten-Free Crust)', 'Cheese (Original Crust)',
       'Cheese (Original or Golden Crust)',
       'Cheese (Original, Golden or Thin Crust)',
       'Cheese (Mozza-Loaded Crust)', 'Cheese (Original or Thin Crust)',
       'All-Meat Combo Pizza (Original Crust)',
       'All-Meat Combo Pizza (Original or Golden Crust)',
       'All-Meat Combo Pizza (Original, Golden or Thin Crust)',
       'All-Meat Combo Pizza (Mozza-Loaded Crust)',
       'Bacon Cheeseburger Pizza (Original Crust)',
       'Bacon Cheeseburger Pizza (Original or Golden Crust)',
       'Bacon Cheeseburger Pizza (Original, Golden or Thin Crust)',
       'Bacon Cheeseburger Pizza (Mozza-Loaded Crust)',
       'Bacon Cheeseburger Pizza (Original or Thin Crust)',
       'Taco Pie Pizza (Original Crust)',
       'Taco Pie Pizza (Original or Golden Crust)',
       'Taco Pie Pizza (Original, Golden or Thin Crust)',
       'Taco Pie Pizza (Mozza-Loaded Crust)',
       'Taco Pie Pizza (Original or Thin Crust)',
       'Classic Combo Pizza (Original Crust)',
       'Classic Combo Pizza (Original or Golden Crust)',
       'Classic Combo Pizza (Original, Golden or Thin Crust)',
       'Classic Combo Pizza (Mozza-Loaded Crust)',
       'Classic Combo Pizza (Original or Thin Crust)',
       'Humble Pie Pizza (Original Crust)',
       'Humble Pie Pizza (Original or Golden Crust)',
       'Humble Pie Pizza (Original, Golden or Thin Crust)',
       'Humble Pie Pizza (Mozza-Loaded Crust)',
       'Humble Pie Pizza (Original or Thin Crust)',
       'Veggie Pie Pizza (Original Crust)',
       'Veggie Pie Pizza (Original or Golden Crust)',
       'Veggie Pie Pizza (Original, Golden or Thin Crust)',
       'Veggie Pie Pizza (Mozza-Loaded Crust)',
       'Veggie Pie Pizza (Original or Thin Crust)',
       'Hot Stuff Pizza (Original Crust)',
       'Hot Stuff Pizza (Original or Golden Crust)',
       'Hot Stuff Pizza (Original, Golden or Thin Crust)',
       'Hot Stuff Pizza (Mozza-Loaded Crust)',
       'Hot Stuff Pizza (Original or Thin Crust)',
       'Hawaiian Pizza (Original Crust)',
       'Hawaiian Pizza (Original or Golden Crust)',
       'Hawaiian Pizza (Original, Golden or Thin Crust)',
       'Hawaiian Pizza (Mozza-Loaded Crust)',
       'Hawaiian Pizza (Original or Thin Crust)',
       'BLT Pizza (Original Crust)',
       'BLT Pizza (Original or Golden Crust)',
       'BLT Pizza (Original, Golden or Thin Crust)',
       'BLT Pizza (Mozza-Loaded Crust)',
       'BLT Pizza (Original or Thin Crust)',
       'Buffalo Chicken Pizza (Original Crust)',
       'Buffalo Chicken Pizza (Original or Golden Crust)',
       'Buffalo Chicken Pizza (Original, Golden or Thin Crust)',
       'Buffalo Chicken Pizza (Mozza-Loaded Crust)',
       'Buffalo Chicken Pizza (Original or Thin Crust)',
       'Super Combo Pizza (Original or Golden Crust)',
       'Super Combo Pizza (Original, Golden or Thin Crust)',
       'Super Combo Pizza (Mozza-Loaded Crust)',
       'Super Combo Pizza (Original or Thin Crust)',
       'Super Hawaiian Pizza (Original or Golden Crust)',
       'Super Hawaiian Pizza (Original, Golden or Thin Crust)',
       'Super Hawaiian Pizza (Mozza-Loaded Crust)',
       'Super Hawaiian Pizza (Original or Thin Crust)',
       'Super Taco Pizza (Original or Golden Crust)',
       'Super Taco Pizza (Original, Golden or Thin Crust)',
       'Super Taco Pizza (Mozza-Loaded Crust)',
       'Super Taco Pizza (Original or Thin Crust)',
       'The Don (Original or Golden Crust)',
       'The Don (Original, Golden or Thin Crust)',
       'The Don (Mozza-Loaded Crust)', 'The Don (Original or Thin Crust)',
       'Super Veggie Pizza (Original or Golden Crust)',
       'Super Veggie Pizza (Original, Golden or Thin Crust)',
       'Super Veggie Pizza (Mozza-Loaded Crust)',
       'Super Veggie Pizza (Original or Thin Crust)',
       'BBQ Bacon Cheeseburger Pizza (Original Crust)',
       'BBQ Bacon Cheeseburger Pizza (Original, Golden or Thin Crust)',
       'BBQ Bacon Cheeseburger Pizza (Mozza-Loaded Crust)',
       'Chipotle Chicken and Bacon Pizza (Original Crust)',
       'Chipotle Chicken and Bacon Pizza (Original, Golden or Thin Crust)',
       'Chipotle Chicken and Bacon Pizza (Mozza-Loaded Crust)',
       'Margherita Pizza (Original, Golden or Thin Crust)',
       'Margherita Pizza (Thin Crust)',
       'Margherita Chicken Pizza (Original, Golden or Thin Crust)',
       'Margherita Chicken Pizza (Thin Crust)', 'Thin Crust',
       'Original Crust', 'Original or Golden Crust',
       'Original, Golden or Thin Crust', 'Mozza-Loaded Crust',
       'Original or Thin Crust', 'Deluxe Pizza', 'Veggie Pizza',
       'Cheese Pizza', 'All Meat Pizza', 'BBQ Chicken Pizza',
       'Egg-Ceptional Pizza']

ordinal=OrdinalEncoder(categories=[pizza])
encoded=ordinal.fit_transform(df[['Pizza Name']])

In [59]:
encoded

array([[  0.],
       [  0.],
       [  0.],
       [  1.],
       [  2.],
       [  2.],
       [  2.],
       [  3.],
       [  3.],
       [  4.],
       [  5.],
       [  6.],
       [  7.],
       [  8.],
       [  9.],
       [ 10.],
       [ 11.],
       [ 12.],
       [ 13.],
       [ 14.],
       [ 15.],
       [ 16.],
       [ 17.],
       [ 18.],
       [ 19.],
       [ 20.],
       [ 21.],
       [ 22.],
       [ 23.],
       [ 24.],
       [ 25.],
       [ 26.],
       [ 27.],
       [ 28.],
       [ 29.],
       [ 30.],
       [ 31.],
       [ 32.],
       [ 33.],
       [ 34.],
       [ 35.],
       [ 36.],
       [ 37.],
       [ 38.],
       [ 39.],
       [ 40.],
       [ 41.],
       [ 42.],
       [ 43.],
       [ 44.],
       [ 45.],
       [ 46.],
       [ 47.],
       [ 48.],
       [ 49.],
       [ 50.],
       [ 50.],
       [ 51.],
       [ 52.],
       [ 53.],
       [ 54.],
       [ 55.],
       [ 55.],
       [ 56.],
       [ 57.],
       [ 58.],
       [ 59.],
       [ 60.],
       [ 60.],
       [ 61.],
       [ 62.],
       [ 63.],
       [ 64.],
       [ 65.],
       [ 66.],
       [ 67.],
       [ 68.],
       [ 69.],
       [ 70.],
       [ 71.],
       [ 72.],
       [ 73.],
       [ 74.],
       [ 75.],
       [ 76.],
       [ 77.],
       [ 78.],
       [ 79.],
       [ 80.],
       [ 80.],
       [ 81.],
       [ 81.],
       [ 81.],
       [ 82.],
       [ 82.],
       [ 83.],
       [ 84.],
       [ 85.],
       [ 85.],
       [ 86.],
       [ 86.],
       [ 86.],
       [ 87.],
       [ 87.],
       [ 88.],
       [ 89.],
       [ 90.],
       [ 90.],
       [ 91.],
       [ 91.],
       [ 91.],
       [ 92.],
       [ 92.],
       [ 93.],
       [ 94.],
       [ 95.],
       [ 95.],
       [ 96.],
       [ 96.],
       [ 96.],
       [ 97.],
       [ 97.],
       [ 98.],
       [ 99.],
       [100.],
       [100.],
       [101.],
       [101.],
       [101.],
       [102.],
       [102.],
       [103.],
       [104.],
       [105.],
       [105.],
       [106.],
       [106.],
       [106.],
       [107.],
       [107.],
       [108.],
       [109.],
       [110.],
       [110.],
       [111.],
       [111.],
       [111.],
       [112.],
       [112.],
       [113.],
       [114.],
       [115.],
       [115.],
       [116.],
       [116.],
       [116.],
       [117.],
       [117.],
       [118.],
       [119.],
       [120.],
       [120.],
       [121.],
       [121.],
       [121.],
       [122.],
       [122.],
       [123.],
       [124.],
       [125.],
       [125.],
       [126.],
       [126.],
       [126.],
       [127.],
       [127.],
       [128.],
       [129.],
       [130.],
       [130.],
       [131.],
       [131.],
       [131.],
       [132.],
       [132.],
       [133.],
       [134.],
       [135.],
       [135.],
       [136.],
       [136.],
       [136.],
       [137.],
       [137.],
       [138.],
       [138.],
       [139.],
       [139.],
       [140.],
       [140.],
       [141.],
       [141.],
       [142.],
       [142.],
       [143.],
       [143.],
       [144.],
       [144.],
       [145.],
       [146.],
       [147.],
       [148.],
       [149.],
       [150.],
       [151.],
       [152.],
       [153.],
       [154.],
       [153.],
       [154.],
       [155.],
       [156.],
       [157.],
       [158.],
       [159.],
       [158.],
       [159.],
       [160.],
       [161.],
       [162.],
       [163.],
       [162.],
       [163.],
       [164.],
       [165.],
       [166.],
       [167.],
       [168.],
       [167.],
       [168.],
       [169.],
       [170.],
       [171.],
       [172.],
       [173.],
       [172.],
       [173.],
       [174.],
       [175.],
       [176.],
       [177.],
       [178.],
       [177.],
       [178.],
       [179.],
       [180.],
       [181.],
       [182.],
       [183.],
       [182.],
       [183.],
       [184.],
       [185.],
       [186.],
       [187.],
       [188.],
       [187.],
       [188.],
       [189.],
       [190.],
       [191.],
       [192.],
       [193.],
       [192.],
       [193.],
       [194.],
       [195.],
       [196.],
       [197.],
       [198.],
       [197.],
       [198.],
       [199.],
       [200.],
       [201.],
       [202.],
       [203.],
       [202.],
       [203.],
       [204.],
       [205.],
       [206.],
       [207.],
       [206.],
       [207.],
       [208.],
       [209.],
       [210.],
       [211.],
       [210.],
       [211.],
       [212.],
       [213.],
       [214.],
       [215.],
       [214.],
       [215.],
       [216.],
       [217.],
       [218.],
       [219.],
       [218.],
       [219.],
       [220.],
       [221.],
       [222.],
       [223.],
       [222.],
       [223.],
       [224.],
       [225.],
       [226.],
       [226.],
       [227.],
       [226.],
       [227.],
       [226.],
       [228.],
       [229.],
       [229.],
       [230.],
       [229.],
       [230.],
       [229.],
       [231.],
       [232.],
       [233.],
       [234.],
       [235.],
       [235.],
       [236.],
       [237.],
       [238.],
       [239.],
       [238.],
       [239.],
       [240.],
       [241.],
       [241.],
       [241.],
       [241.],
       [242.],
       [242.],
       [242.],
       [242.],
       [243.],
       [243.],
       [243.],
       [243.],
       [244.],
       [244.],
       [244.],
       [244.],
       [245.],
       [245.],
       [245.],
       [245.],
       [246.],
       [246.],
       [246.],
       [246.]])

In [60]:
Pizza_name = pd.DataFrame(encoded,columns=['Encoded'])

In [61]:
df['Pizza Name']= Pizza_name

In [62]:
df['Pizza Name']

0        0.0
1        0.0
2        0.0
3        1.0
4        2.0
       ...
366    245.0
367    246.0
368    246.0
369    246.0
370    246.0
Name: Pizza Name, Length: 371, dtype: float64

In [63]:
df.head()

   Company  Pizza Name           Type          Size   Price
0      0.0         0.0  Cheeses Pizza   Small (10")  $5.99
1      0.0         0.0  Cheeses Pizza  Medium (12")  $7.99
2      0.0         0.0  Cheeses Pizza   Large (14")  $9.99
3      0.0         1.0  Cheeses Pizza  Medium (12")  $7.99
4      0.0         2.0  Cheeses Pizza   Small (10")  $5.99

In [64]:
typ=['Cheeses Pizza', 'Specialty Pizzas', 'Feast Pizzas',
       'Cheese Pizza', 'Classic Recipe Pizzas', 'New Recipe Pizzas',
       'Skinny Pizzas', 'Gluten-Free Pizzas', 'Express Favorites']
ordinal=OrdinalEncoder(categories=[typ])
encoded=ordinal.fit_transform(df[['Type']])

In [65]:
encoded

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [4.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [6.],
       [6.],
       [6.],
       [6.],
       [6.],
       [7.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [7.],
       [7.],
       [8.],
       [8.],
       [8.],
       [8.],
       [8.],
       [8.],
       [8.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [66]:
encoded_type = pd.DataFrame(encoded,columns=['Encoded'])

In [67]:
df.Type = encoded_type

In [68]:
df.Type

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
366    1.0
367    1.0
368    1.0
369    1.0
370    1.0
Name: Type, Length: 371, dtype: float64

In [69]:
df.head()

   Company  Pizza Name  Type          Size   Price
0      0.0         0.0   0.0   Small (10")  $5.99
1      0.0         0.0   0.0  Medium (12")  $7.99
2      0.0         0.0   0.0   Large (14")  $9.99
3      0.0         1.0   0.0  Medium (12")  $7.99
4      0.0         2.0   0.0   Small (10")  $5.99

In [70]:
size1 =['Small (10")', 'Medium (12")', 'Large (14")', 'X-Large (16")',
       'Medium', 'Large', 'Personal', 'Small', 'Mini', 'Jumbo',
       'X Large (16")'] 
ordinal = OrdinalEncoder(categories=[size1])
encoded = ordinal.fit_transform(df[['Size']])

In [71]:
encoded

array([[ 0.],
       [ 1.],
       [ 2.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 0.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 5.],
       [ 7.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 4.],
       [ 5.],
       [ 8.],
       [ 7.],
       [ 4.],
       [ 4.],
       [ 5.],
       [ 5.],
       [ 9.],
       [ 0.],
       [ 1.],
       [ 2.],
       [10.],
       [ 0.],
       [ 1.],
       [ 2.],
       [10.],
       [ 0.],
       [ 1.],
       [ 2.],
       [10.],
       [ 0.],
       [ 1.],
       [ 2.],
       [10.],
       [ 0.],
       [ 1.],
       [ 2.],
       [10.],
       [ 0.],
       [ 1.],
       [ 2.],
       [10.]])

In [72]:
encoded_size = pd.DataFrame(encoded,columns=['Encoded'])

In [73]:
df.Size=encoded_size

In [74]:
df.Size

0       0.0
1       1.0
2       2.0
3       1.0
4       0.0
       ...
366    10.0
367     0.0
368     1.0
369     2.0
370    10.0
Name: Size, Length: 371, dtype: float64

In [75]:
df.head()

   Company  Pizza Name  Type  Size   Price
0      0.0         0.0   0.0   0.0  $5.99
1      0.0         0.0   0.0   1.0  $7.99
2      0.0         0.0   0.0   2.0  $9.99
3      0.0         1.0   0.0   1.0  $7.99
4      0.0         2.0   0.0   0.0  $5.99

# Replace

In [76]:
df['Price']=df['Price'].str.replace('$','').astype('float64')

In [77]:
df['Price']

0       5.99
1       7.99
2       9.99
3       7.99
4       5.99
       ...
366    23.85
367    11.80
368    14.95
369    18.65
370    22.30
Name: Price, Length: 371, dtype: float64

In [78]:
df.head()

   Company  Pizza Name  Type  Size  Price
0      0.0         0.0   0.0   0.0   5.99
1      0.0         0.0   0.0   1.0   7.99
2      0.0         0.0   0.0   2.0   9.99
3      0.0         1.0   0.0   1.0   7.99
4      0.0         2.0   0.0   0.0   5.99